## 创建数组
在ipython中可以使用命令 `%pylab` 快速导入numpy相关的库

In [1]:
%pylab

Using matplotlib backend: Qt4Agg
Populating the interactive namespace from numpy and matplotlib


### 数学上的操作
创建一个数组

In [2]:
a = array([1,2,3,4])
a

array([1, 2, 3, 4])

变为一个2×2的多维数组

In [3]:
a.shape = 2,2
a

array([[1, 2],
       [3, 4]])

数组的加减乘除

In [4]:
b = array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [5]:
a + b

array([[ 6,  8],
       [10, 12]])

In [6]:
a * b

array([[ 5, 12],
       [21, 32]])

In [7]:
a / b

array([[ 0.2       ,  0.33333333],
       [ 0.42857143,  0.5       ]])

可见都是对应位置的元素进行加减乘除

### 提取数组中的元素
**注意：下标都是从0开始的**

In [8]:
c = array([[1,2,3],[4,5,6],[7,8,9]])
c[0,0]

1

In [9]:
c[:2]

array([[1, 2, 3],
       [4, 5, 6]])

## 基础数据类型
Python支持的数据类型有整型、浮点型以及复数型，不足以满足科学计算的需要，Numpy支持如下数据类型:

![pic](datatype.png)

例如：

In [10]:
d = array([1+2j,3+4j])
d.dtype

dtype('complex128')

In [11]:
e = array([True,False])
e.dtype

dtype('bool')

也可以自定义数据类型，例如：

In [12]:
f= array([1,2,3], dtype=float)
f.dtype

dtype('float64')

默认的数据类型是浮点型

In [13]:
g = ones((3,3))
g

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [14]:
g.dtype

dtype('float64')

## 索引与切片

In [15]:
h = arange(10)
h

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
h[0],h[2]

(0, 2)

h[start:end:step]

In [17]:
h[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [18]:
h[2:9:3]

array([2, 5, 8])

In [19]:
i = diag(arange(4))
i

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3]])

In [20]:
i[2,1]=10
i

array([[ 0,  0,  0,  0],
       [ 0,  1,  0,  0],
       [ 0, 10,  2,  0],
       [ 0,  0,  0,  3]])

通过下图可以简单理解Numpy的索引与切片：

![pic](indexing.png)

## 切片机制
切片只是在原数组上的一个引用，因此原数组在内存上不会被复制，可以用may_share_memory()来检查两个数组是否共用一个内存。如果b是a数组的一个切片，那么b只是指向a所在内存，当我们改变b时，a的值也会改变。

In [21]:
a = arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
b=a[::2]
b

array([0, 2, 4, 6, 8])

In [23]:
may_share_memory(a,b)

True

In [24]:
b[1]=10
b

array([ 0, 10,  4,  6,  8])

In [25]:
a

array([ 0,  1, 10,  3,  4,  5,  6,  7,  8,  9])

可以使用copy()命令来强制产生一个复制，在修改数据时，原数据将不会被改变

In [26]:
c = a[::2].copy()
may_share_memory(a,c)

False

## Fancy indexing
通过布尔值来索引切片

In [27]:
a = random.random_integers(0, 20, 15)
a

array([ 1,  1,  8,  8,  3,  9,  4,  8, 10,  2,  1,  5, 12,  5, 17])

In [28]:
a % 3== 0 

array([False, False, False, False,  True,  True, False, False, False,
       False, False, False,  True, False, False], dtype=bool)

In [29]:
mask = (a % 3 == 0)
a[mask]

array([ 3,  9, 12])

通过数组来索引切片

In [30]:
a[[2,3,2,5]] 

array([8, 8, 8, 9])

In [31]:
b = array(linspace(1,10,5), dtype=int)
b

array([ 1,  3,  5,  7, 10])

In [32]:
idx = array([[1,2],
           [2,4]])
b[idx]

array([[ 3,  5],
       [ 5, 10]])

利用下图来简单理解fancy indexing

![pic](fancyindexing.png)

参考：[1.3.1. The Numpy array object](http://www.scipy-lectures.org/intro/numpy/array_object.html#basic-visualization)