## 创建数组
在ipython中可以使用命令 `%pylab` 快速导入numpy相关的库

In [1]:
%pylab

Using matplotlib backend: Qt4Agg
Populating the interactive namespace from numpy and matplotlib


### 数学上的操作
创建一个数组

In [2]:
a = array([1,2,3,4])
a

array([1, 2, 3, 4])

变为一个2×2的多维数组

In [3]:
a.shape = 2,2
a

array([[1, 2],
       [3, 4]])

数组的加减乘除

In [4]:
b = array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [5]:
a + b

array([[ 6,  8],
       [10, 12]])

In [6]:
a * b

array([[ 5, 12],
       [21, 32]])

In [7]:
a / b

array([[ 0.2       ,  0.33333333],
       [ 0.42857143,  0.5       ]])

可见都是对应位置的元素进行加减乘除

### 提取数组中的元素
**注意：下标都是从0开始的**

In [8]:
c = array([[1,2,3],[4,5,6],[7,8,9]])
c[0,0]

1

In [9]:
c[:2]

array([[1, 2, 3],
       [4, 5, 6]])

## 基础数据类型
Python支持的数据类型有整型、浮点型以及复数型，不足以满足科学计算的需要，Numpy支持如下数据类型:

![pic](datatype.png)

例如：

In [10]:
d = array([1+2j,3+4j])
d.dtype

dtype('complex128')

In [11]:
e = array([True,False])
e.dtype

dtype('bool')

也可以自定义数据类型，例如：

In [12]:
f= array([1,2,3], dtype=float)
f.dtype

dtype('float64')

默认的数据类型是浮点型

In [13]:
g = ones((3,3))
g

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [14]:
g.dtype

dtype('float64')