In [1]:
import numpy as np

## 改变形状

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [3]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [5]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [6]:
a.shape

(2, 3)

In [8]:
b = a.ravel()
b = b.reshape((3,2))
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
b.reshape((2,-1)) # 使用-1来不指定列，自动判断有几列

array([[1, 2, 3],
       [4, 5, 6]])

同样的，reshape也只是改变了指向，修改数据时，原数据也会被改变

In [13]:
b[0,0] = 9
b

array([[9, 2],
       [3, 4],
       [5, 6]])

In [14]:
a

array([[9, 2, 3],
       [4, 5, 6]])

## 增加维度
使用np.newaxis来增加数组的一个轴

In [16]:
c = np.array([1,2,3,4])
c[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4]])

In [17]:
c[np.newaxis, :]

array([[1, 2, 3, 4]])

In [25]:
a = np.arange(4*3*2).reshape(4,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [26]:
b = a.transpose(2,1,0) #numpy.transpose(a, axes=None)
b

array([[[ 0,  6, 12, 18],
        [ 2,  8, 14, 20],
        [ 4, 10, 16, 22]],

       [[ 1,  7, 13, 19],
        [ 3,  9, 15, 21],
        [ 5, 11, 17, 23]]])

## 改变长度


In [30]:
a = np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

已经被引用的数组不能被改变长度