## 数据类型转换
赋值时不会改变数据类型

In [2]:
import numpy as np
a = np.array([1,2,3])
a[0] = 1.9
a

array([1, 2, 3])

在数组类型的混合操作时，“Bigger type”更胜一筹

In [3]:
np.array([1, 2, 3]) + 1.5

array([ 2.5,  3.5,  4.5])

强制转换

In [7]:
a = np.array([1.3,1.3,1.5])
a.astype(int)

array([1, 1, 1])