## 数据类型转换
赋值时不会改变数据类型

In [1]:
import numpy as np
a = np.array([1,2,3])
a[0] = 1.9
a

array([1, 2, 3])

在数组类型的混合操作时，“Bigger type”更胜一筹

In [2]:
np.array([1, 2, 3]) + 1.5

array([ 2.5,  3.5,  4.5])

强制转换

In [3]:
a = np.array([1.3,1.3,1.5])
a.astype(int)

array([1, 1, 1])

## 结构化数组
假设我们要保存一组这样的数据：

||No|Name|Score|
|-----|------|------|------|
|0|001|long|99.2|
|1|002|chan|98.5|
|2|003|luo|88.9|

定义一个一维数组，每个数组有No、Name、Score三个属性

In [4]:
sample = np.empty((3, ), dtype=[('No', 'S3'), ('Name', 'S4'), ('Score', float)])
sample

array([(b'', b'', 1.3059271491859664e-308),
       (b'd\n', b'd\x06\x00e', 4.731541533670325e-309),
       (b'\x83\x01\x01', b'Z\x03\x00d', 4.731541527518323e-309)], 
      dtype=[('No', 'S3'), ('Name', 'S4'), ('Score', '<f8')])

In [5]:
sample.dtype.names

('No', 'Name', 'Score')

In [6]:
sample['No'] = ['001', '002', '003']
sample

array([(b'001', b'', 1.3059271491859664e-308),
       (b'002', b'd\x06\x00e', 4.731541533670325e-309),
       (b'003', b'Z\x03\x00d', 4.731541527518323e-309)], 
      dtype=[('No', 'S3'), ('Name', 'S4'), ('Score', '<f8')])

In [7]:
sample[:] = [('001','long', 99.2), ('002', 'chan', 98.5), ('003', 'luo', 88.9)]
sample

array([(b'001', b'long', 99.2), (b'002', b'chan', 98.5),
       (b'003', b'luo', 88.9)], 
      dtype=[('No', 'S3'), ('Name', 'S4'), ('Score', '<f8')])

In [8]:
sample['Name']

array([b'long', b'chan', b'luo'], 
      dtype='|S4')

In [9]:
sample[1]['Name']

b'chan'

排序：

In [10]:
sample.sort(order='Name')
sample

array([(b'002', b'chan', 98.5), (b'001', b'long', 99.2),
       (b'003', b'luo', 88.9)], 
      dtype=[('No', 'S3'), ('Name', 'S4'), ('Score', '<f8')])

In [11]:
print (sample)

[(b'002', b'chan', 98.5) (b'001', b'long', 99.2) (b'003', b'luo', 88.9)]
